// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.MtbSchool.Domain.Models;

public partial class CourseEdition
{
    public int Id { get; set; }

    public int CourseId { get; set; }

    public DateTime DateFrom { get; set; }

    public DateTime DateTo { get; set; }

    public string Locality { get; set; }

    public string Instructions { get; set; }

    public int PhotoGalleryId { get; set; }

    public virtual Course Course { get; set; }

    public virtual PhotoGallery PhotoGallery { get; set; }

    public virtual ICollection<Participant> Participants { get; set; } = new List<Participant>();

    public virtual ICollection<Trainer> Trainers { get; set; } = new List<Trainer>();
}