// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.MtbSchool.Domain.Models;

public partial class Course
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? PhotoGalleryId { get; set; }

    public virtual ICollection<CourseEdition> CourseEditions { get; set; } = new List<CourseEdition>();

    public virtual PhotoGallery PhotoGallery { get; set; }
}