// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.MtbSchool.Domain.Models;

public partial class Participant
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Address { get; set; }

    public string PostalCode { get; set; }

    public string City { get; set; }

    public string CountryId { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string MobilePhone { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public int? BikeLevel { get; set; }

    public string Language { get; set; }

    public virtual ICollection<TourParticipant> TourParticipants { get; set; } = new List<TourParticipant>();

    public virtual ICollection<CourseEdition> Courses { get; set; } = new List<CourseEdition>();
}