// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.MtbSchool.Domain.Models;

public partial class PhotoGallery
{
    public int Id { get; set; }

    public string Title { get; set; }

    public DateTime? Date { get; set; }

    public string Description { get; set; }

    public string Thumbnail { get; set; }

    public string Url { get; set; }

    public bool? OnHomePage { get; set; }

    public string Slug { get; set; }

    public virtual ICollection<CourseEdition> CourseEditions { get; set; } = new List<CourseEdition>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<Page> Pages { get; set; } = new List<Page>();

    public virtual ICollection<Photo> Photos { get; set; } = new List<Photo>();

    public virtual ICollection<Tour> Tours { get; set; } = new List<Tour>();
}