// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.MtbSchool.Domain.Models;

public partial class Photo
{
    public int Id { get; set; }

    public int? PhotoGalleryId { get; set; }

    public int? Running { get; set; }

    public string Filename { get; set; }

    public string Caption { get; set; }

    public string LinkUrl { get; set; }

    public string LinkTitle { get; set; }

    public bool? OnHomePage { get; set; }

    public virtual PhotoGallery PhotoGallery { get; set; }
}