// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RizSoft.MtbSchool.Domain.Models;

public partial class TourParticipant
{
    public int TourId { get; set; }

    public int ParticipantId { get; set; }

    public virtual Participant Tour { get; set; }

    public virtual Tour TourNavigation { get; set; }
}